USE [dbName]
GO

CREATE TABLE [dbo].[AmazonEC2](
	[SKU] [nvarchar](150) NOT NULL,
	[OfferTermCode] [nvarchar](150) NOT NULL,
	[RateCode] [nvarchar](150) NOT NULL,
	[TermType] [nvarchar](150) NOT NULL,
	[PriceDescription] [nvarchar](150) NOT NULL,
	[EffectiveDate] [datetime2](7) NOT NULL,
	[StartingRange] [nvarchar](150) NULL,
	[EndingRange] [nvarchar](150) NULL,
	[Unit] [nvarchar](150) NOT NULL,
	[PricePerUnit] [nvarchar](150) NOT NULL,
	[Currency] [nvarchar](150) NOT NULL,
	[LeaseContractLength] [nvarchar](150) NULL,
	[PurchaseOption] [nvarchar](150) NULL,
	[OfferingClass] [nvarchar](150) NULL,
	[Product Family] [nvarchar](150) NOT NULL,
	[serviceCode] [nvarchar](150) NOT NULL,
	[Location] [nvarchar](150) NULL,
	[Location Type] [nvarchar](150) NULL,
	[Instance Type] [nvarchar](150) NULL,
	[Current Generation] [nvarchar](150) NULL,
	[Instance Family] [nvarchar](150) NULL,
	[vCPU] [nvarchar](150) NULL,
	[Physical Processor] [nvarchar](150) NULL,
	[Clock Speed] [nvarchar](150) NULL,
	[Memory] [nvarchar](150) NULL,
	[Storage] [nvarchar](150) NULL,
	[Network Performance] [nvarchar](150) NULL,
	[Processor Architecture] [nvarchar](150) NULL,
	[Storage Media] [nvarchar](150) NULL,
	[Volume Type] [nvarchar](150) NULL,
	[Max Volume Size] [nvarchar](150) NULL,
	[Max IOPS/volume] [nvarchar](150) NULL,
	[Max IOPS Burst Performance] [nvarchar](150) NULL,
	[Max throughput/volume] [nvarchar](150) NULL,
	[Provisioned] [nvarchar](150) NULL,
	[Tenancy] [nvarchar](150) NULL,
	[EBS Optimized] [nvarchar](150) NULL,
	[Operating System] [nvarchar](150) NULL,
	[License Model] [nvarchar](150) NULL,
	[Group] [nvarchar](150) NULL,
	[Group Description] [nvarchar](150) NULL,
	[Transfer Type] [nvarchar](150) NULL,
	[From Location] [nvarchar](150) NULL,
	[From Location Type] [nvarchar](150) NULL,
	[To Location] [nvarchar](150) NULL,
	[To Location Type] [nvarchar](150) NULL,
	[usageType] [nvarchar](150) NULL,
	[operation] [nvarchar](150) NULL,
	[CapacityStatus] [nvarchar](150) NULL,
	[Dedicated EBS Throughput] [nvarchar](150) NULL,
	[ECU] [nvarchar](150) NULL,
	[Elastic GPU Type] [nvarchar](150) NULL,
	[Enhanced Networking Supported] [nvarchar](150) NULL,
	[GPU] [nvarchar](150) NULL,
	[GPU Memory] [nvarchar](150) NULL,
	[Instance] [nvarchar](150) NULL,
	[Instance Capacity - 10xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 12xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 16xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 18xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 24xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 2xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 32xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 4xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 8xlarge] [nvarchar](150) NULL,
	[Instance Capacity - 9xlarge] [nvarchar](150) NULL,
	[Instance Capacity - large] [nvarchar](150) NULL,
	[Instance Capacity - medium] [nvarchar](150) NULL,
	[Instance Capacity - xlarge] [nvarchar](150) NULL,
	[Intel AVX Available] [nvarchar](150) NULL,
	[Intel AVX2 Available] [nvarchar](150) NULL,
	[Intel Turbo Available] [nvarchar](150) NULL,
	[Normalization Size Factor] [nvarchar](150) NULL,
	[Physical Cores] [nvarchar](150) NULL,
	[Pre Installed S/W] [nvarchar](150) NULL,
	[Processor Features] [nvarchar](150) NULL,
	[serviceName] [nvarchar](150) NOT NULL
) ON [PRIMARY]
GO

